export enum ICON_ID {
  None = 0,
  Github = 1,
  Linkedin = 2,
  Mail = 3,
  ExternalLink = 4,
  ChevronsUp = 5,
  ChevronsDown = 6,
  Smile = 7,
  Code = 8,
  Handshake = 9,
  Sparkles = 10,
  EyeOff = 11,
  Eye = 12,
  MousePointerClick = 13,
  Hourglass = 14,
  Shell = 15,
}
